export const NFT_LABEL = 'NFT';
export const TOKEN_LABEL = 'TOKEN';

export const HTTP_CODES = {
  BAD_REQUEST: 400,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};
