export const PUB_API_ERROR_CODES = {
  ONE_FREE_ADDRESS_PER_DOMAIN_ERROR: 'ONE_FREE_ADDRESS_PER_DOMAIN_ERROR',
  REF_NOT_FOUND: 'REF_NOT_FOUND',
  // TODO check is real needed
  // SALE_IS_CLOSED: 'SALE_IS_CLOSED',
  // TODO check is real needed
  // PRICE_AMOUNT_ERROR: 'PRICE_AMOUNT_ERROR',
  INVALID_FIO_NAME: 'INVALID_FIO_NAME',
  NO_PUBLIC_KEY_SPECIFIED: 'NO_PUBLIC_KEY_SPECIFIED',
  // TODO check is real needed
  // DOMAIN_IS_NOT_REGISTERED: 'DOMAIN_IS_NOT_REGISTERED',
  DOMAIN_IS_NOT_PUBLIC: 'DOMAIN_IS_NOT_PUBLIC',
  DOMAIN_IS_ALREADY_REGISTERED: 'DOMAIN_IS_ALREADY_REGISTERED',
  // TODO check is real needed
  // DOMAIN_IS_NOT_ALLOWED_FOR_REF: 'DOMAIN_IS_NOT_ALLOWED_FOR_REF',
  ADDRESS_CANT_BE_RENEWED: 'ADDRESS_CANT_BE_RENEWED',
  ADDRESS_IS_ALREADY_REGISTERED: 'ADDRESS_IS_ALREADY_REGISTERED',
  // TODO check is real needed
  // REGISTRATION_NOT_AVAILABLE: 'REGISTRATION_NOT_AVAILABLE',
  SERVER_ERROR: 'SERVER_ERROR',
  // TODO replaces by apiKey validation
  // CAPTCHA_FAILED: 'CAPTCHA_FAILED',
  ALREADY_SENT_REGISTRATION_REQ_FOR_DOMAIN: 'ALREADY_SENT_REGISTRATION_REQ_FOR_DOMAIN',
}
