import {
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faAt,
  faBackspace,
  faBan,
  faBell,
  faCheck,
  faCheckCircle,
  faCheckSquare,
  faChevronDown,
  faChevronRight,
  faChevronUp,
  faCircle,
  faCog,
  faDollarSign,
  faDownload,
  faEnvelope,
  faExchangeAlt,
  faExclamationCircle,
  faExclamationTriangle,
  faExternalLinkSquareAlt,
  faEye,
  faEyeSlash,
  faImage,
  faInfinity,
  faInfoCircle,
  faKey,
  faKeyboard,
  faLink,
  faPen,
  faPlusCircle,
  faPlusSquare,
  faQrcode,
  faSearch,
  faShareAlt,
  faShoppingCart,
  faSignature,
  faSpinner,
  faTimesCircle,
  faTrash,
  faUserCircle,
  faWallet,
} from '@fortawesome/free-solid-svg-icons';

import {
  faCircle as faRegularCircle,
  faClipboard as faRegularClipboard,
  faCopy as faRegularCopy,
  faSquare as faRegularSquare,
} from '@fortawesome/free-regular-svg-icons';

const icons = {
  faEye,
  faEyeSlash,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faBackspace,
  faCog,
  faBell,
  faCircle,
  faRegularClipboard,
  faShoppingCart,
  faTimesCircle,
  faInfoCircle,
  faBan,
  faChevronUp,
  faChevronDown,
  faChevronRight,
  faUserCircle,
  faKeyboard,
  faCheckCircle,
  faRegularCircle,
  faSpinner,
  faExclamationCircle,
  faSearch,
  faPlusSquare,
  faTrash,
  faWallet,
  faPlusCircle,
  faExclamationTriangle,
  faLink,
  faAt,
  faCheckSquare,
  faRegularSquare,
  faCheck,
  faSignature,
  faPen,
  faEnvelope,
  faRegularCopy,
  faImage,
  faExchangeAlt,
  faDownload,
  faShareAlt,
  faQrcode,
  faKey,
  faDollarSign,
  faExternalLinkSquareAlt,
  faInfinity,
};

export default icons;
