version: '3'

services:
  api:
    container_name: fio-dashboard-api
    build: .
    command: npm run server:dev
    volumes:
      - ./server:/usr/app/server
      - ./.env:/usr/app/.env
      - /usr/app/node_modules
    ports:
      - 9006:9006
    depends_on:
      - postgres
    environment:
      - SQL_HOST=fio-dashboard-postgres

  postgres:
    container_name: fio-dashboard-postgres
    image: postgres:14.12-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ab1f6hh942sm
      POSTGRES_USER: fio_dash_sql_user
      POSTGRES_DB: fio_dash_db
