export const LINK_LABELS = {
  HOME: 'Home',
  DASHBOARD: 'Dashboard',
  NOTIFICATIONS: 'Notifications',
  SETTINGS: 'Settings',
  PROFILE: 'My profile',
  ABOUT_US: 'About Us',
  CONTACT_US: 'Contact Us',
  FIO_ADDRESSES: 'FIO Addresses',
  FIO_DOMAINS: 'FIO Domains',
  FIO_REQUESTS: 'FIO Requests',
  FIO_WALLET: 'FIO Wallet',
  GOVERNANCE: 'Governance',
  PROTOCOL_UPDATES: 'Protocol Updates',
};
