const ROUTES = {
  HOME: '/',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  DASHBOARD: '/dashboard',
  CONFIRM_EMAIL: '/confirmEmail/:hash',
  PROFILE: '/profile',
  RESET_PASSWORD: '/reset-password/:hash',
  PASSWORD_RECOVERY: '/password-recovery',
  CREATE_ACCOUNT: '/create-account',
  FIO_ADDRESSES_SELECTION: '/fio-addresses-selection',
  FIO_DOMAINS_SELECTION: '/fio-domains-selection',
  FIO_ADDRESSES: '/fio-addresses',
  FIO_DOMAINS: '/fio-domains',
  FIO_REQUESTS: '/fio-requests',
  FIO_WALLET: '/fio-wallet',
  GOVERNANCE: '/governance',
  PROTOCOL_UPDATES: '/protocol-updates',
  CART: '/cart',
  CHECKOUT: '/checkout',
  PURCHASE: '/purchase',
  FIO_ADDRESS_OWNERSHIP: '/fio-address-ownership',
  FIO_DOMAIN_OWNERSHIP: '/fio-domain-ownership',
  FIO_DOMAIN_STATUS_CHANGE: '/fio-domain-status-change',
};

export { ROUTES };
