export const WS_ENDPOINTS = {
  NOTIFICATIONS: 'NOTIFICATIONS',
  ORDER_STATUS: 'ORDER_STATUS',
};

export const AUTH_REQ_ENDPOINTS = {
  [WS_ENDPOINTS.NOTIFICATIONS]: true,
  [WS_ENDPOINTS.ORDER_STATUS]: true,
};
