import db from '../db';

export const {
  Action,
  AdminUser,
  AdminUsersRole,
  AdminUsersStatus,
  BlockchainTransaction,
  BlockchainTransactionEventLog,
  ChainCode,
  Contact,
  FioAccountProfile,
  FioApiUrl,
  FreeAddress,
  LockedFch,
  NewDeviceTwoFactor,
  Nonce,
  Notification,
  Order,
  OrderItem,
  OrderItemStatus,
  Payment,
  PaymentEventLog,
  PublicWalletData,
  ReferrerProfile,
  TokenCode,
  User,
  Var,
  Wallet,
  WrapStatusBlockNumbers,
  WrapStatusEthUnwrapLogs,
  WrapStatusNetworks,
  WrapStatusPolygonUnwrapLogs,
  WrapStatusEthWrapLogs,
  WrapStatusPolygonWrapLogs,
  WrapStatusFioUnwrapNftsLogs,
  WrapStatusFioUnwrapTokensLogs,
  WrapStatusFioWrapNftsLogs,
  WrapStatusFioWrapTokensLogs,
  WrapStatusFioUnwrapNftsOravotes,
  WrapStatusFioUnwrapTokensOravotes,
  WrapStatusEthOraclesConfirmationsLogs,
  WrapStatusPolygonOraclesConfirmationsLogs,
  Domain,
  SearchTerm,
  Username,
} = db.models;
