import db from '../db';

export const {
  Action,
  ActionLimit,
  AdminUser,
  AdminUsersRole,
  AdminUsersStatus,
  BlockchainTransaction,
  BlockchainTransactionEventLog,
  Cart,
  ChainCode,
  Contact,
  Domain,
  DomainsWatchlist,
  FioAccountProfile,
  FioApiUrl,
  FreeAddress,
  GatedRegistrtionTokens,
  LockedFch,
  NewDeviceTwoFactor,
  Nonce,
  Notification,
  Order,
  OrderItem,
  OrderItemStatus,
  Payment,
  PaymentEventLog,
  PublicWalletData,
  ReferrerProfile,
  ReferrerProfileApiToken,
  SearchTerm,
  TokenCode,
  User,
  UserDevice,
  Username,
  Var,
  Wallet,
  WrapStatusBlockNumbers,
  WrapStatusEvmChainEvents,
  WrapStatusFioChainEvents,
  WrapStatusNetworks,
} = db.models;
